### ISSUE TITLE
Possibility to Choose Classic Chess Pieces?

### ISSUE THREAD

**Issue by chiweb7** [FrenchYann/Chess3D#3]
Hi
The game is really cool! Incredible Graphics and the chess engine is tough.
But can you add the possibility to choose classic chess pieces. I think most chess players will be more familiar wit the classic pieces.
Regards.

**Comment by FrenchYann** [comment]
Hi,
I probably won't do it, since it's a project I did long ago and I don't plan to go back to it.
The tools used to convert models to three.js compatible format should be referenced somewhere in the repo, so anyone could probably change the models with a little bit of effort.
And if you want a template selection menu in the UI... well... a little bit more effort :D
Thanks.
